### ISSUE TITLE
Does not read archive-portfolio.php

### ISSUE THREAD

**Issue by hadokee** [devinsays/portfolio-post-type#72]
Hello, I added archive-portfolio.php file to customize portfolio category page but it doesn't work.
Wordpress does not read the file.

**Comment by devinsays** [comment]
archive-portfolio.php is used for the post type archive, but not for the taxonomies. archive.php is used for taxonomies unless you have a template specifically for that taxonomy. You can see how the template hierarchy works here: http://codex.wordpress.org/Template_Hierarchy

In Portfolio Press I use a filter to override the default behavior, so that I can use archive-portfolio.php. Here's some info on how to make filter like that: http://wptheming.com/2014/02/template-hijacking-and-useful-styling-tricks/
